<a href="https://colab.research.google.com/github/ThangDoan2001/API-Python-Learn/blob/master/Homeworks_12_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# câu 1 : import module numpy và in ra version 

import numpy as np
print(np.__version__)

# python 3.8 +
from importlib_metadata import version 
print(version('numpy'))

1.19.5
1.19.5


In [4]:
# câu 2 : Tạo mảng 1 chiều từ 0 đến 9

import numpy as np
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# câu 3: Tạo một mảng boolean 3x3 với tất cả giá trị là True

import numpy as np

# Cách 1 :

arr = np.ones((3, 3)) > 0
print(arr)
# Cách 2 : 
arr = np.ones((3, 3), dtype=bool)
print(arr)
# Cách 3:
arr = np.full(shape=(3,3), fill_value=True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# câu 4 : Lấy những phần tử mà thoả mãn một điều kiện cho trước của mảng một chiều

import numpy as np

# tạo mảng một chiều từ 0 đến 9
data = np.arange(0, 10, 1)
# Tìm phần tử có giá rị lẻ 
odds = data[data%2 == 1]
odds

array([1, 3, 5, 7, 9])

In [15]:
# câu 5 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác

import numpy as np

# tạo mảng một chiều từ 0 đến 9
data = np.arange(0, 10, 1)
# cách 1
print(np.where(data%2 == 1, -1, data))
# Thay thế phần tử có giá trị lẻ bằng -1
data[data%2==1] = -1
print(data)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [17]:
# câu 6 : Thay thế phần tử thoả mãn điều kiện cho trước bằng 1 một giá khác 
# nhưng không thay đổi mảng ban đầu

# Thay thế tất cả số lẻ bằng giá trị -1 nhưng mảng ban đầu không thay đổi

import numpy as np

# tạo mảng một chiều từ 0 đến 9
arr = np.arange(0, 10)
# arr_copy = arr
arr_copy = arr.copy()
arr_copy[arr % 2 == 1] = -1
print(arr)
print(arr_copy);
# Cách 2 :
arr_copy2 = np.where(arr%2==1, -1, arr)
print(arr_copy2)



[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [19]:
# câu 7 : Định dạng/chuyển mảng

# Chuyển mảng 1 chiều thành mảng 2 chiều có 2 hàng ( dòng )

import numpy as np

# tạo mảng 1d gồm 10 phần tử
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# mảng 2 chiều có 2 hàng
print(arr.reshape((2, -1)))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
# câu 8:  xếp chồng 2 mảng theo chiều dọc

import numpy as np

# tạo data
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(a)
print(b)
# Cách 1 : 
c = np.concatenate([a, b], axis = 0)
print(c)
# Cách 2 : 
d = np.vstack([a, b])
print(d)
# Cách 3 : 
e = np.r_[a, b]
print(e)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
# câu 9 : xếp chồng 2 mảng theo chiều ngang

import numpy as np

# tạo data
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(a)
print(b)
# Cách 1 : 
c = np.concatenate([a, b], axis = 1)
print(c)
# Cách 2 : 
d = np.hstack([a, b])
print(d)
# Cách 3 : 
e = np.c_[a, b]
print(e)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [29]:
# câu 10

import numpy as np

# chỉ dùng hàm numpy có sẵn với mảng a như bên dưới
a = np.array([1,2,3])
print(a)

# tạo mảng mới lặp lại mỗi phần tử lên 3 lần
b = np.repeat(a, 3)
print(b)
# tạo mảng mới lặp lại mảng tất cả phần tử lên 3 lần
c = np.tile(a, (1, 3))
print(c)
d = np.tile(a, (3, 1))
print(d)

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[[1 2 3 1 2 3 1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
# câu 11: Lấy phần tử chung của 2 mảng a và b 

import numpy as np

a = np.array([1,2,3,2,3,4,3,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Lấy phần tử chung của 2 mảng a và b 
np.intersect1d(a, b)
# Find unique, different elements

array([2, 4])

In [32]:
# câu 12 : Xoá phần tử từ 1 mảng mà tồn tại trong 1 mảng khác

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Từ mảng a xoá tất cả các phần tử mà đã có trong mảng b
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [33]:
# câu 13: 

import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Lấy tất cả vị trí nơi giá trị các phần tử của 2 mảng a,b giống nhau
np.where(a==b)

(array([1, 3, 5, 7]),)

In [40]:
# câu 14 : Lấy tất cả các giá trị trong 1 phạm vi cho trước từ 1 mảng

import numpy as np

a = np.array([2,6,1,9,10,3,27])

# tìm tất cả vị trí của các phần tử có giá trị trong phạm vi [5,10]
b = a[np.where((a>=5)&(a<=10))]
print(b)

c = a[(a>=5)&(a<=10)]
print(c)

d = a[np.where(np.logical_and(a>=5, a<=10))]
print(d)

[ 6  9 10]
[ 6  9 10]
[ 6  9 10]


In [43]:
# câu 15 : Tạo hàm xử lý trên mảng numpy

import numpy as np

def maxx(x,y):
    # Lấy số lớn nhất nhất trong 2 số
    if x >= y :
        return x
    else:
        return y

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

# numpy.vectorize lấy hàm maxx: x,y và biến nó thành maxx: a[] -> b[].
pair_max = np.vectorize(maxx, otypes=[float])
c = pair_max(a, b)
print(c)


[6. 7. 9. 8. 9. 7. 5.]
[6 7 9 8 9 7 5]


In [48]:
import numpy as np

# lấy giá trị lớn hơn giữa a và b
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])


# dùng hàm maximum để
c = np.maximum(a, b, dtype=float)
print(c)

# dùng hàm where 
d = np.where(a < b, b, a)
print(d)

[6. 7. 9. 8. 9. 7. 5.]
[6 7 9 8 9 7 5]


In [51]:
# câu 16 : Hoán các cột trong mảng 2 chiều 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)

# Hoán cột có index 0 và index 1 trong mảng arr
arr[:, [1, 0, 2]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [55]:
# câu 17 :  Hoán 2 hàng trong mảng 2 chiều 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)
print(arr)

# Hoán dòng có index 0 và index 1 trong mảng arr
arr[[1,0,2], :]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [61]:
# câu 18 : 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)
print(arr)
# Đoản ngược hàng (dòng) trong mảng 2 chiều
print(arr[::-1])
print(arr[:, ::-1])
print(arr[::-1, :])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [62]:
# câu 19 

import numpy as np

# cho mảng arr có shape 3x3
arr = np.arange(9).reshape(3,3)

# Đoản ngược cột trong mảng 2 chiều
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [66]:
# Câu 20 :  Tạo mảng 2 chiều chứa số random kiểu float từ 5 đến 10

import numpy as np


# Tạo mảng 2 chiều 5x3 từ 5 đến 10
# Cách Dùng hàm random.uniform 
ar = np.random.uniform(5,10,size=(5,3))
ar

array([[5.79905927, 6.7246582 , 6.03606274],
       [5.1175771 , 5.45901967, 9.99184753],
       [8.82969353, 8.37467504, 6.37307083],
       [9.66242922, 8.92619297, 5.67848442],
       [6.94592479, 9.7596621 , 5.68674827]])

In [69]:
# câu 21 

import numpy as np

# cho mảng a chứa các số ngẫu nhiên từ [1, 50)
a = np.random.uniform(1,50,20)
print(a)

# Thay thế tất cả các giá trị lớn hơn một giá trị cho trước thành một phạm vi [10,30]
# Thay thế tất cả các giá trị lớn hơn 30 thành 30 và dưới 10 thành 10
# Cách 1 : dùng hàm np.clip  
b = np.clip(a, 10., 30.)
print(b)

# Cách 2 : dùng hàm np.where
c = np.where(a < 10, 10, np.where(a > 30, 30, a))
print(c)


[48.82513337 27.01742057 38.77289978 32.90673242 14.43781982 21.04848797
 37.83199226 20.90545098 11.23486383 48.70748491 30.95158523 37.07968164
  6.51600378  6.869717   14.19241712 40.6967339  14.66947925 23.03253354
 21.92820931  6.44606434]
[30.         27.01742057 30.         30.         14.43781982 21.04848797
 30.         20.90545098 11.23486383 30.         30.         30.
 10.         10.         14.19241712 30.         14.66947925 23.03253354
 21.92820931 10.        ]
[30.         27.01742057 30.         30.         14.43781982 21.04848797
 30.         20.90545098 11.23486383 30.         30.         30.
 10.         10.         14.19241712 30.         14.66947925 23.03253354
 21.92820931 10.        ]


In [82]:
# câu 22: Lấy vị trí của n giá trị đứng đầu từ một mảng numpy

import numpy as np

# cho mảng a chứa các số ngẫu nhiên từ [1, 50)
a = np.random.uniform(1,50, 20)
print(a)


# Cách 1 : dùng hàm np.argsort() 
ind = np.argsort(a)[-5:]
print(a[np.argsort(a)[-5:]])
# Cách 2 : dùng hàm sort() 
np.argpartition(a, -5)
print(a[np.argpartition(a, 5)][-5:])

[29.74191821 36.41467837 28.29861126 27.4954968  14.86872031 48.97456479
 15.14208524 15.53126087 49.43483995 30.85256545 48.65595739 25.56580225
  8.84576259 14.60116457 11.51560468 18.32138012 13.51175019 37.47735707
  6.30883114 28.29507247]
[36.41467837 37.47735707 48.65595739 48.97456479 49.43483995]
[36.41467837 49.43483995 37.47735707 48.97456479 30.85256545]


In [108]:
# câu 23: Chuyển đổi một mảng chứa nhiều mảng thành một mảng 1d phẳng

import numpy as np


# cho array_of_arrays như sau
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
d = np.concatenate(array_of_arrays)
print(d)
# Chuyển đổi array_of_arrays thành mảng 1d tuyến tính phẳng 
e = np.hstack(array_of_arrays)
print(e)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # This is added back by InteractiveShellApp.init_path()


In [91]:
# câu 24: Tìm giá trị lớn nhất trong mỗi hàng của mảng 2d 

import numpy as np

# cho mảng a
a = np.random.randint(1, 10, [5,3])
print(a)


# Cách 1 : dùng np.amax
b = np.amax(a, axis=1)
print(b)

#Cách 2 : dung np.apply_along_axis và np.max
c = np.apply_along_axis(np.max, axis=1, arr=a)
print(c)


[[2 6 1]
 [6 5 9]
 [6 4 9]
 [7 2 9]
 [4 7 5]]
[6 9 9 9 7]
[6 9 9 9 7]


In [112]:
# câu 25

import numpy as np

# cho mảng a
a = np.random.randint(1, 10, [5,3])
print(a)

# tính tỉ số min/max cho mỗi hàng trong mảng a
b = np.min(a, axis=1)/np.max(a, axis = 1)
print(b)


[[1 3 5]
 [1 7 5]
 [4 7 6]
 [1 6 1]
 [6 8 4]]
[0.2        0.14285714 0.57142857 0.16666667 0.5       ]


In [115]:
# câu 26: Tìm các vị trí có giá trị trùng lặp trong một mảng numpy

import numpy as np

# cho mảng a
a = np.random.randint(0, 5, 10)
print(a)

# Tìm các phần tử trùng lặp (lần xuất hiện thứ 2 trở đi) trong mảng đã cho
# và đánh dấu chúng là True. Lần đầu tiên xuất hiện là False.

# hint: dùng np.full và np.unique
b = np.full(a.shape[0], True)

unique_a, return_index = np.unique(a, return_index=True)

b[return_index] = False
b



[2 0 2 4 1 3 0 2 0 1]


array([False, False,  True, False, False, False,  True,  True,  True,
        True])

In [93]:
# câu 27: loại bỏ tất cả các giá trị còn thiếu (np.nan) trong một mảng

import numpy as np

# cho mảng a
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

# bỏ tất cả các giá trị nan từ một mảng numpy 1D
a[np.logical_not(np.isnan(a))]

array([1., 2., 3., 5., 6., 7.])

In [84]:
# câu 28: 

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# tính khoảng cách giữa hai mảng a và b, dùng np.linalg.norm
np.linalg.norm(a-b)


6.708203932499369

In [88]:
# câu 29: Tìm tất cả các cực đại cục bộ (hay còn gọi các đỉnh) trong một mảng 1d

import numpy as np



# cho mảng a như sau
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Tìm tất cả các đỉnh trong một mảng numpy 1D. 
# Đỉnh là các điểm được bao quanh bởi các giá trị nhỏ hơn ở cả hai phía.
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations
# hint: dùng np.diff và np.sign


array([2, 5])