<a href="https://colab.research.google.com/github/ThangDoan2001/API-Python-Learn/blob/master/Numpy_Lesson_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
l = [1, 2, 3, 4]
print(type(l))
l = np.array(l)
print(type(l))

<class 'list'>
<class 'numpy.ndarray'>


# Common attributes

1. dtype
2. shape
3. ndim

In [2]:
list3d = [[[1, 6], [2, 2], [3, 4]],
          [[4, 7], [5, 2], [6, 9]],
          [[7, 7], [8, 2], [9, 5]]]
data = np.array(list3d)
data.dtype, data.shape, data.ndim

(dtype('int64'), (3, 3, 2), 3)

Trong python mọi thứ đều là một object, kể cá a = 5 thì cũng là một object

# Create Numpy array
1. zeros()
2. ones()
3. full()
4. arange()
5. eye()
6. random.random()

In [5]:
# zeros () function
zero_arr = np.zeros((2, 3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# ones() function
arr = np.ones((2, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# full() function
arr = np.full((2, 3), 9)
arr

array([[9, 9, 9],
       [9, 9, 9]])

In [8]:
# arange() function
arr1 = np.arange(5)
arr2 = np.arange(0, 5, 2)
arr1, arr2

(array([0, 1, 2, 3, 4]), array([0, 2, 4]))

In [9]:
# eye() function
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# random() function
arr = np.random.random((2, 3))
arr

array([[0.52008754, 0.63917391, 0.087384  ],
       [0.9920145 , 0.94533677, 0.00935907]])

# Some important function

1. clip()
2. np.linalg.inv()
3. hstack()
4. vstack()
5. concatenate()
6. np.newaxis
7. apply_along_axis()
8. where()
9. flatten()
10. reshape()
11. dot()
12. sum()


In [13]:
# clip() -> xứ lí outlier, threshold....,

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = np.clip(data, a_min=3, a_max=6)
result

array([3, 3, 3, 4, 5, 6, 6, 6, 6])

In [15]:
result = np.clip(data, a_min=[3, 4, 1, 1, 1, 4, 4, 4, 4], a_max=9)
result

array([3, 4, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# hstack() - kết hợp theo chiều ngang 

In [17]:
# vstack() - kết hợp theo chiều dọc

In [24]:
# concatenate()
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 4, 5])
np.concatenate((arr1, arr2), axis=0)

array([1, 2, 3, 3, 4, 5])

In [25]:
# np.concatenate((arr1, arr2), axis=1) -> lỗi vì chỉ có một chiều 

In [26]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[3, 4, 5]])
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 3, 3, 4, 5]])

In [28]:
# np.newaxis -> thêm số chiều 
arr = np.array([1, 2, 3, 4, 5])
arr[:, np.newaxis], arr[np.newaxis, :]

(array([[1],
        [2],
        [3],
        [4],
        [5]]), array([[1, 2, 3, 4, 5]]))

# Khi thay đổi của data1 thì data2 (numpy sinh ra từ numpy1 mà liên quan đến các hành động liên quan đến dấu : vd numpy1[:]) -> sẽ thay đổi theo


In [30]:
a_list = [1, 2, 3]
data1 = np.array(a_list)
data2 = data1[:, np.newaxis]

In [33]:
# apply_along_axis() function
data = np.array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3 ,4],
        [1, 2, 3, 4]])

result = np.apply_along_axis(np.max,
                             axis=1,
                             arr=data)
result

array([4, 4, 4, 4])

In [35]:
# np.vectorize()
def compare(a, b):
  if a >= b:
    return 0
  else:
    return 1

compare_vec = np.vectorize(compare)
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 0, 1, 4])
compare_vec(arr1, arr2)

array([1, 1, 0, 0, 0])

In [36]:
arr1 > arr2

array([False, False,  True,  True,  True])

In [39]:
# where()
arr = np.arange(5)
out = np.where(arr < 3, arr, arr*2) # Sai thực hiện cái trước, đúng thực hiện cái sau
out


array([0, 1, 2, 6, 8])

In [40]:
# flatten() function
arr = np.array([[1, 2], [3, 4]])
arr.flatten()

array([1, 2, 3, 4])

In [41]:
# reshape()
arr.reshape(1, 4)

array([[1, 2, 3, 4]])

# Array Indexing


In [47]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
# C1 : giảm chiều
print(arr[1, :])
# C2: ko đổi chiều
print(arr[1:2, :])

[4 5 6]
[[4 5 6]]


In [48]:
# C1: 
print(arr[:, 1])
# C2:
print(arr[:, 1:2])

[2 5 8]
[[2]
 [5]
 [8]]


In [49]:
# dot()
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 0, 1, 4])
arr1.dot(arr2)

32

In [50]:
arr1 = np.array([[1, 2, 3, 4, 5],
                 [2, 3, 0, 1, 4]])
arr2 = np.array([2, 3, 0, 1, 4])
arr1.dot(arr2)

array([32, 30])

In [51]:
X = np.array([[1, 2],
             [3, 4]])
X.dot(X), X.dot(X.T)

(array([[ 7, 10],
        [15, 22]]), array([[ 5, 11],
        [11, 25]]))

In [52]:
# np.sum()
np.sum(X, axis = 0) # sum each column

array([4, 6])

In [53]:
np.sum(X, axis = 1) # sum each row

array([3, 7])